# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URLs": "01_environ_covariates.ipynb",
         "n": "01_environ_covariates.ipynb"}

modules = ["env_data.py"]

doc_url = "https://qAp.github.io/earthshotsoil/"

git_url = "https://github.com/qAp/earthshotsoil/tree/master/"

def custom_doc_links(name): return None
