# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Path.ls": "00_core.ipynb",
         "jargon": "jargon.ipynb"}

modules = ["core.py",
           "jargon.py"]

doc_url = "https://qAp.github.io/earthshotsoil/"

git_url = "https://github.com/qAp/earthshotsoil/tree/master/"

def custom_doc_links(name): return None
