# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_core.ipynb (unless otherwise specified).

__all__ = []

# Cell
import os
from pathlib import Path
import shutil

# Cell
Path.ls = lambda p: list(p.iterdir())

def _cp(src, dst):
    assert src.is_file()
    shutil.copy(src, dst)