# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_environ_covariates.ipynb (unless otherwise specified).

__all__ = ['URLs', 'n', 'n']

# Cell
import os
from urlpath import URL
import easydict
import requests
import math
import numpy as np
import xarray as xr
import rioxarray

# Cell
URLs = easydict.EasyDict()

# Cell
n = 'EarthEnvCloudCover_MODCF_interannualSD'
URLs[n] = URL('https://data.earthenv.org/cloud/'
           'MODCF_interannualSD.tif')

# Cell
n = 'EarthEnvCloudCover_MODCF_intraannualSD'
URLs[n] = URL('https://data.earthenv.org/cloud/'
           'MODCF_intraannualSD.tif')