# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/jargon.ipynb (unless otherwise specified).

__all__ = ['jargon']

# Cell
jargon = {}

# Cell
jargon['FAO'] = ('Food and Agriculture Organization'
                 ' of the United Nations')

# Cell
jargon['SEP'] = ('Sustainable Enterprise Project')